'''
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DO NOT EDIT THIS FILE
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'''

from cmath import exp
import io
from unittest import mock, TestCase
from temperature import calculate_average_temperature

class TestTemperatureAverage(TestCase):

    @mock.patch('sys.stdout', new_callable=io.StringIO)
    def test_calculate_average_temperature(self, mock_stdout):
        # Test case 1
        temperatures1 = [20.5, 22.0, 18.5, 25.5, 26.0, 23.5, 19.0]
        result1 = calculate_average_temperature(temperatures1)
        self.assertAlmostEqual(result1, 22.142857142857142, places=6)

        # Test case 2
        temperatures2 = [-10.0, 0.0, 10.0, 20.0, 30.0, 40.0, 40.0]
        result2 = calculate_average_temperature(temperatures2)
        self.assertAlmostEqual(result2, 18.571428571428573, places=6)

        # Test case 3: Average of all zeros
        temperatures3 = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        result3 = calculate_average_temperature(temperatures3)
        self.assertEqual(result3, 0.0)

        # Test case 4: Empty list
        temperatures4 = []
        result4 = calculate_average_temperature(temperatures4)
        self.assertIsNone(result4)  # Check that result is None for an empty list


     